# Generated by Django 5.2.4 on 2025-07-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('camp_pic', models.FileField(default='', upload_to='camp_pic/')),
                ('from_date', models.CharField(max_length=10)),
                ('to_date', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
    ]
