# Generated by Django 5.2.4 on 2025-07-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0004_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='venue',
            field=models.TextField(default=''),
        ),
    ]
