# Generated by Django 5.2.4 on 2025-07-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0005_alter_campaign_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='query',
            new_name='comment',
        ),
    ]
