# Generated by Django 5.2.4 on 2025-07-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0006_rename_query_contact_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='remarks',
            new_name='remark',
        ),
    ]
