# Generated by Django 5.2.4 on 2025-08-04 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0007_rename_remarks_feedback_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_pic', models.FileField(default='', upload_to='advisory_pic/')),
                ('service_description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=10)),
                ('aadhaar', models.CharField(default='', max_length=10)),
                ('transaction_id', models.CharField(default='', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo_app.user')),
            ],
        ),
    ]
