# Generated by Django 5.2.4 on 2025-08-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0008_service_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
