# Generated by Django 5.2.4 on 2025-08-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo_app', '0014_alter_donation_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='aadhaar',
            field=models.FileField(default='', upload_to='aadhar/'),
        ),
    ]
